# Runs all tests 
name: All Tests

on:  # Runs on any push event to any branch except master (the coverage workflow takes care of that)
  push:
    branches-ignore:
      - 'master'

jobs:
  tests:
    uses: pylhc/.github/.github/workflows/tests.yml@master
